ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER javaproject_8919 IDENTIFIED BY password;

GRANT CREATE SESSION TO javaproject_8919;

GRANT CREATE TABLE TO javaproject_8919;

ALTER USER javaproject_8919 QUOTA UNLIMITED ON USERS;

